keys:
- &thelegy CC340A1392661DD38B0DE83DABB80FCB4FFE0BC5

- &agony 954ab1770044b7bc35bfa2b004bb211e9f8ae7c3
- &forever 739759680da462402111a08f4081a822387c18d0
- &migrator 1db99b44ae18613145dd110bf226588d3e6e2294
- &roborock 2d59898b69126a28647dda7de82e1978fd768662
- &sirrah ab9a4004133c9e02091db7e53b6203a9abeb522d
- &th1 efb1200339303eab0ac3ce783c966b47b84d969e
- &y c611f29dbc693fae526f32433869ef25ac9942dc

creation_rules:
- path_regex: machines/agony/.*
  key_groups:
  - pgp:
    - *thelegy
    - *agony
- path_regex: machines/forever/.*
  key_groups:
  - pgp:
    - *thelegy
    - *forever
- path_regex: machines/migrator/.*
  key_groups:
  - pgp:
    - *thelegy
    - *migrator
- path_regex: machines/roborock/.*
  key_groups:
  - pgp:
    - *thelegy
    - *roborock
- path_regex: machines/sirrah/.*
  key_groups:
  - pgp:
    - *thelegy
    - *sirrah
- path_regex: machines/th1/.*
  key_groups:
  - pgp:
    - *thelegy
    - *th1
- path_regex: machines/y/.*
  key_groups:
  - pgp:
    - *thelegy
    - *y
- pgp:
  key_groups:
  - pgp:
    - *thelegy
