# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    "pcie_rockchip_host"
    "phy_rockchip_pcie"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/38f880c7-ab8a-4f1b-be04-f87318bdf31a";
    fsType = "btrfs";
    options = [ "noatime" "discard=async" "subvol=roborock" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F099-4E41";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/aa8039bf-0145-40a4-bc65-3137f67d49da"; } ];

  nix.settings.max-jobs = lib.mkDefault 6;
  powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
}
